---
# handlers file for sshd
#
- name: "Restart firewalld"
  service:
    name: "firewalld"
    state: "restarted"
  listen: "restart firewalld"

- name: "Restart sshd"
  service:
    name: "sshd"
    state: "restarted"
  listen: "restart sshd"

- name: "Set ansible_port to configured value"
  set_fact:
    ansible_port: "{{sshd_port}}"
  listen: "restart sshd"

- name: "Check we can connect to SSH"
  become: no
  local_action:
    module: "wait_for"
    host: "{{ansible_host}}"
    port: "{{ansible_port}}"
    state: "started"
    connect_timeout: 1
    delay: 5
    timeout: 30

